name: Build and test Dice
on: [push]
env:
  REGISTRY: ghcr.io

jobs:
  test-linux:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-24.04-arm, ubuntu-22.04-arm]
        build_type: [ "Debug", "Release" ]
        cfg:
        - cc: gcc
          cxx: g++
        - cc: clang
          cxx: clang++
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure
        run: cmake -S. -Bbuild
             -DCMAKE_INSTALL_PREFIX=/tmp/target
             -DCMAKE_C_COMPILER=${{ matrix.cfg.cc }}
             -DCMAKE_CXX_COMPILER=${{ matrix.cfg.cxx }}
             -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - name: Build
        run: cmake --build build
      - name: Test
        run: ctest --test-dir build --output-on-failure
      - name: Install
        run: cmake --install build

  test-sanitizer:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        sanitizer: [thread, address, undefined]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure
        run: cmake -S. -Bbuild
             -DDICE_SANITIZER=${{matrix.sanitizer}}
             -DCMAKE_C_COMPILER=gcc
             -DCMAKE_CXX_COMPILER=g++
      - name: Build
        run: cmake --build build
      - name: Test
        run: ctest --test-dir build --output-on-failure

  test-alpine:
    runs-on: ubuntu-latest
    container: ghcr.io/open-s4c/dice/alpine-ci:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure
        run: cmake -S. -Bbuild
             -DCMAKE_INSTALL_PREFIX=/tmp/target
      - name: Build
        run: cmake --build build
      - name: Test
        run: ctest --test-dir build --output-on-failure
      - name: Install
        run: cmake --install build

  test-macos:
    if: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure
        run: cmake -S. -Bbuild
             -DCMAKE_INSTALL_PREFIX=/tmp/target
      - name: Build
        run: cmake --build build
      - name: Test
        run: ctest --test-dir build --output-on-failure
      - name: Install
        run: cmake --install build
